Repository CodeGrind-Team/CodeGrind-Bot, pull requests merged in 2023-08, with the labels that each got.

#54 [Shaan] Added Streaks, Milestones & Verified Roles
  bot_globals.py
  cogs/roles.py
  cogs/users.py
  embeds/general_embeds.py
  embeds/roles_embeds.py
  models/user_model.py
  utils/message_scheduler.py
  utils/roles.py
  utils/stats.py
  utils/views.py
Labels: enhancement, good first issue

#58 [Shaan] Updated ReadME
  README.md
Labels: enhancement

#66 Use default intents and validate the channel's existence
  bot_globals.py
  tests/send_notification.py
  utils/leaderboards.py
  utils/message_scheduler.py
Labels: bug

#68 Fix typo in account_not_found_embed
  embeds/users_embeds.py
Labels: bug
